#!/usr/bin/env ruby

require 'rubygems'
require 'bundler/setup'
require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))
require 'mailman'

Mailman.config.pop3 = {
  username: ENV["GMAIL_USERNAME"],
  password: ENV["GMAIL_PASSWORD"],
  server: 'pop.gmail.com', port: 995, ssl: true
}

Mailman::Application.run do
  default do
    Email.create subject: message.subject, body_plain: message.body.decoded, from: message.from.first
  end
end